"""delete colomn all_price from basket table

Revision ID: 6029f0ecfe94
Revises: a30a812d9d86
Create Date: 2024-07-01 12:27:13.781426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6029f0ecfe94'
down_revision: Union[str, None] = 'a30a812d9d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baskets', 'all_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baskets', sa.Column('all_price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
